### ISSUE TITLE
Does not work with tsify 0.16.0

### ISSUE THREAD

**Issue by IngvarKofoed** [cmlenz/tsify-test#2]
First, very nice work!! )

I tried upgrading to a newer version of tsify but then you example stops working :(

Below is a snip of the errors from karma. It seems that tsify starts parsing node_modules. I also tried to exclude this folder in tsconfig.json, but then the function 'describe' is unknown.

```
[31m01 07 2016 12:23:24.764:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.764:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(83,5): Error TS2300: Duplicate identifier 'enumerable'.
[31m01 07 2016 12:23:24.764:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.764:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(84,5): Error TS2300: Duplicate identifier 'value'.
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(85,5): Error TS2300: Duplicate identifier 'writable'.
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(96,5): Error TS2300: Duplicate identifier 'constructor'.
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(132,5): Error TS2300: Duplicate identifier 'prototype'.
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(251,5): Error TS2300: Duplicate identifier 'prototype'.
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(252,5): Error TS2300: Duplicate identifier 'length'.
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(255,5): Error TS2300: Duplicate identifier 'arguments'.
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.765:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(256,5): Error TS2300: Duplicate identifier 'caller'.
[31m01 07 2016 12:23:24.766:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.766:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(266,5): Error TS2300: Duplicate identifier 'prototype'.
[31m01 07 2016 12:23:24.766:ERROR [framework.browserify]: [39mbundle error
[31m01 07 2016 12:23:24.766:ERROR [framework.browserify]: [39mTypeScript error: node_modules/typescript/lib/lib.core.d.ts(273,5): Error TS2300: Duplicate identifier 'length'.
[31m01 07 2016 12:23:24.766:ERROR [framework.browserify]: [39mbundle error

```

**Comment by cmlenz** [comment]
PR merged.
